---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aiops-scaler-sa
  namespace: aiops

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aiops-scaler-clusterrole
rules:
- apiGroups: ["apps"]
  resources: ["deployments/scale", "deployments"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aiops-scaler-clusterbinding
subjects:
- kind: ServiceAccount
  name: aiops-scaler-sa
  namespace: aiops
roleRef:
  kind: ClusterRole
  name: aiops-scaler-clusterrole
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiops-scaler
  namespace: aiops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiops-scaler
  template:
    metadata:
      labels:
        app: aiops-scaler
    spec:
      serviceAccountName: aiops-scaler-sa
      containers:
      - name: scaler
        image: michonszy/scaler:0.0.5
        env:
        - name: GRAFANA_INSTANCE_ID
          valueFrom:
            secretKeyRef:
              name: grafana-cloud-credentials
              key: GRAFANA_INSTANCE_ID
        - name: PROMETHEUS_URL
          valueFrom:
            secretKeyRef:
              name: grafana-cloud-credentials
              key: PROMETHEUS_URL
        - name: GRAFANA_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: grafana-cloud-credentials
              key: GRAFANA_ACCESS_TOKEN
        - name: METRIC_MAX_AGE_SECONDS
          value: "1200"
        - name: BASELINE_MIN_REPLICAS
          value: "1"
        - name: LOWER_STEP
          value: "1"